 while(i >= -10) 
{         i--;     } }  
2) 1)
  int age; 
    cout << "Enter age: ";   
  cin >> age;    
 while (age < 1 || age > 100) { 
  cout << "Invalid range. Enter age: ";         cin >> age;     }    
 cout << "You entered a correct age of " << age << endl; 
2)
 int sum =0;
for(int i = 1;i <=10; ++I){sum += I}
Cout << sum << endl;
3)
void input(string & license, string &name)
	{
	cout << “Enter the name”:; cin >> name;
	cout << “Enter the license plate :” can >> license;
	{
	int main()
	{
string name,license;
input (license,name);
cout << “ UserName:” << name << endl;
cout <<“License plate “ << license;
4)
bool even(int n)
{
if(n%2==0){
return true;
}
else{
return false;
}
}
int main()
{
int n;
cout<<"Enter a n : ";cin>>n;
if(even(n))
{
